<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * Vendors Phosphor icons as Blade components.
 *
 * Legacy hand-drew its icons into `web/partials/icons/`, so needing a new one
 * meant drawing it. Phosphor gives a consistent set for both halves of the app —
 * `@phosphor-icons/vue` in the dashboard, these in Blade.
 *
 * Copied in rather than pulled in as a package: the set is 1,512 icons per
 * weight and the site uses five. `@phosphor-icons/core` is a devDependency, so
 * nothing here is needed at runtime or on a deploy.
 *
 * Add a name to `ICONS` and re-run.
 */
class SyncIcons extends Command
{
	protected $signature = 'icons:sync {--weight=regular}';

	protected $description = 'Copy the Phosphor icons this app uses into Blade components';

	/**
	 * Every icon the application uses, by its Phosphor name.
	 *
	 * @var array<int, string>
	 */
	private const ICONS = [
		'arrow-right',
		'list',
		'shopping-cart',
		'user',
		'x',
	];

	public function handle(): int
	{
		$weight = (string) $this->option('weight');
		$source = base_path("node_modules/@phosphor-icons/core/assets/{$weight}");

		if (! is_dir($source)) {
			$this->error("No Phosphor assets at {$source}. Run `npm install` first.");

			return self::FAILURE;
		}

		$target = resource_path('views/components/icon');
		@mkdir($target, 0755, true);

		foreach (self::ICONS as $name) {
			$file = "{$source}/{$name}.svg";

			if (! is_file($file)) {
				$this->error("{$name}: not in the {$weight} set; skipped");

				continue;
			}

			file_put_contents("{$target}/{$name}.blade.php", $this->component($file, $weight));
			$this->line("  {$name}");
		}

		$this->info(count(self::ICONS).' icons written to resources/views/components/icon.');

		return self::SUCCESS;
	}

	private function component(string $file, string $weight): string
	{
		$svg = trim((string) file_get_contents($file));

		// Phosphor ships a transparent <rect> to pad the viewBox. It does
		// nothing here and confuses `currentColor` inspection.
		$svg = (string) preg_replace('#\s*<rect[^>]*fill="none"[^>]*/>#', '', $svg);

		// Fixed dimensions would beat the size class.
		$svg = (string) preg_replace('#\s(width|height)="[^"]*"#', '', $svg);

		// The caller sets the size and anything else; `size-24` is the default
		// because that is what the header uses.
		$svg = Str::replaceFirst(
			'<svg ',
			"<svg {{ \$attributes->merge(['class' => 'size-24', 'aria-hidden' => 'true']) }} ",
			$svg,
		);

		$header = <<<BLADE
		{{-- Phosphor "{$weight}", vendored from @phosphor-icons/core.
		     Generated by `php artisan icons:sync` — do not hand-edit. --}}

		BLADE;

		return $header.$svg."\n";
	}
}
